
# (currentLevel) * (scoreToLevelModifier) => nextLevelRemainingScore
level-base-score: 3
score-to-level-modifier: 1.5

levels:
  "1":
    format: "&7[Lv.{level}]&r"
  "10":
    format: "&f[Lv.{level}]&r"
  "20":
    format: "&e[Lv.{level}]&r"
