name: CELevelSystem
version: '${version}'
main: com.gmail.necnionch.myplugin.celevelsystem.bukkit.LevelSystemPlugin
api-version: 1.13
depend: [ CommandAPI, LuckPerms, N8ChatCaster ]
authors: [ Necnion8 ]
